# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here 
      #https://discuss.circleci.com/t/php-apache-selenium-apachephp-does-not-get-environment-vars/2618
      #- image: circleci/php:7.2-apache-browsers
      #  environment:
      #    DB_STRING:                  mysql:host=127.0.0.1;dbname=eoo_test
       #   DB_USER:                    root
        #  DB_PASSWORD:                test
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - run: sudo apt-get install apache2
      - run: sudo service apache2 start
      - run: sudo npm install
      - run: sudo npm install -g @angular/cli > /dev/null --save
      - run: sudo npm install  @angular/cli > /dev/null --save
      
      - run: sudo npm install -g --save @angular/compiler  > /dev/null
      - run: sudo npm install --save @angular/compiler  > /dev/null 

      - run: sudo npm install -g @angular-devkit/build-angular
      - run: sudo npm install @angular-devkit/build-angular
      
      - run: sudo npm install   --save-dev @angular/cli > /dev/null
            
      - run: sudo npm install
      - run: echo "coucou"
      - run: ls
      - run: pwd
      
       #wget vs
      - run: curl http://localhost/index.html
      
      - run: sudo npm install -g @angular/compiler-cli > /dev/null --save
      - run: sudo npm install  @angular/compiler-cli > /dev/null --save
      
      - run: cd bookshelves ; ls ; ng serve
      
     
      


      # run tests!
      #- run: yarn test
      
  #https://circleci.com/docs/2.0/workflows/#workflows-configuration-examples    
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: sudo npm install -g @angular/cli

      - run: ng serve
#https://circleci.com/docs/2.0/workflows/#workflows-configuration-examples
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build
